export const ADD_STAFF = 'ADD_STAFF'
export const UPDATE_STAFF = 'UPDATE_STAFF'
export const REMOVE_STAFF = 'REMOVE_STAFF'
export const REPLACE_STAFF = 'REPLACE_STAFF'

export const FETCH_COURSES_REQUEST = 'FETCH_COURSES_REQUEST'
export const FETCH_COURSES_SUCCESS = 'FETCH_COURSES_SUCCESS'
export const FETCH_COURSES_FAILURE = 'FETCH_COURSES_FAILURE'

export const FETCH_COURSE_REQUEST = 'FETCH_COURSE_REQUEST'
export const FETCH_COURSE_SUCCESS = 'FETCH_COURSE_SUCCESS'
export const FETCH_COURSE_FAILURE = 'FETCH_COURSE_FAILURE'

export const FETCH_QUEUE_REQUEST = 'FETCH_QUEUE_REQUEST'
export const FETCH_QUEUE_SUCCESS = 'FETCH_QUEUE_SUCCESS'
export const FETCH_QUEUE_FAILURE = 'FETCH_QUEUE_FAILURE'

export const CREATE_COURSE_REQUEST = 'CREATE_COURSE_REQUEST'
export const CREATE_COURSE_SUCCESS = 'CREATE_COURSE_SUCCESS'
export const CREATE_COURSE_FAILURE = 'CREATE_COURSE_FAILURE'

export const CREATE_QUEUE_REQUEST = 'CREATE_QUEUE_REQUEST'
export const CREATE_QUEUE_SUCCESS = 'CREATE_QUEUE_SUCCESS'
export const CREATE_QUEUE_FAILURE = 'CREATE_QUEUE_FAILURE'

export const DELETE_QUEUE_REQUEST = 'DELETE_QUEUE_REQUEST'
export const DELETE_QUEUE_SUCCESS = 'DELETE_QUEUE_SUCCESS'
export const DELETE_QUEUE_FAILURE = 'DELETE_QUEUE_FAILURE'

export const FETCH_QUESTIONS_REQUEST = 'FETCH_QUESTIONS_REQUEST'
export const FETCH_QUESTIONS_SUCCESS = 'FETCH_QUESTIONS_SUCCESS'
export const FETCH_QUESTIONS_FAILURE = 'FETCH_QUESTIONS_FAILURE'

export const CREATE_QUESTION_REQUEST = 'CREATE_QUESTION_REQUEST'
export const CREATE_QUESTION_SUCCESS = 'CREATE_QUESTION_SUCCESS'
export const CREATE_QUESTION_FAILURE = 'CREATE_QUESTION_FAILURE'

export const UPDATE_QUESTION_ANSWERING_REQUEST = 'UPDATE_QUESTION_ANSWERING_REQUEST'
export const UPDATE_QUESTION_ANSWERING_SUCCESS = 'UPDATE_QUESTION_ANSWERING_SUCCESS'
export const UPDATE_QUESTION_ANSWERING_FAILURE = 'UPDATE_QUESTION_ANSWERING_FAILURE'

export const DELETE_QUESTION_REQUEST = 'DELETE_QUESTION_REQUEST'
export const DELETE_QUESTION_SUCCESS = 'DELETE_QUESTION_SUCCESS'
export const DELETE_QUESTION_FAILURE = 'DELETE_QUESTION_FAILURE'


/* These events will be fired on websocket messages */
export const UPDATE_QUESTIONS = 'UPDATE_QUESTIONS'
export const UPDATE_QUEUES = 'UPDATE_QUEUES'
