development:
  dialect:   sqlite
  storage:   ./dev.sqlite
  benchmark: true
  logging:   false

test:
  dialect: sqlite
  storage: ":memory:"
  logging: false

staging:
  dialect: sqlite
  storage: ./staging.sqlite
  logging: false

production:
  dialect:  mysql
  username: root
  password: ???
  database: database_production
  host:     127.0.0.1
